# Dependencies
# markdown:         kramdown
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:             SUNlightMOON
# tagline:          'A Jekyll theme'
description:      '이것저것 스터디 중입니다.. 나중에 무엇이 되려고 이럴까요??ㅎㅎ'
# url:              http://hyde.getpoole.com
# baseurl:          /

# author:
#  name:           'Mark Otto'
  url:            https://sm-mobius.github.io

3paginate:         5

# Custom vars
# version:          2.1.0

# github:
#  repo:           https://github.com/poole/hyde
# TTT EEE SSS TTT
