# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sm-mobius
tagline:          'A Jekyll theme'
description:      'TTEESSTT A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://sm-mobius.github.io
baseurl:          https://sm-mobius.github.io

author:
  name:           'test'
  url:            https://sm-mobius.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:           https://sm-mobius.github.io
  repo:           https://github.com/poole/hyde
