# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sunlightmoon
tagline:          'hello there'
description:      'sm test'
url:              https://sm-mobius.github.io
baseurl:          

author:
  name:           'sunlightmoon'
  url:            https://sm-mobius.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:           https://sm-mobius.github.io
  repo:           
